/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpairing;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Shaun
 */
public class JPairingFrame extends javax.swing.JFrame implements TableModelListener {

    private playerTableModel playerDataModel;
    private pairingTableModel pairingDataModel;
    private TournamentClass tournamentDetails;

    /**
     * Creates new form JPairingFrame
     */
    public JPairingFrame() {
        playerDataModel = new playerTableModel();
        pairingDataModel = new pairingTableModel();
        playerDataModel.addBlankRow();
        initComponents();
        playerDataTable.getModel().addTableModelListener(this);
        
        
    }
    
    @Override
     public void tableChanged(TableModelEvent e) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        if (column == -1) {
            column = 0;
        }
        TableModel model = (TableModel)e.getSource();
        String columnName = model.getColumnName(column);
        Object data = model.getValueAt(row, column);

        // Do something with the data...
    }
     
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerDataTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        addPlayerButton = new javax.swing.JButton();
        deletePlayerButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        automaticPairButton = new javax.swing.JButton();
        updatePairButton = new javax.swing.JButton();
        modifyPairButton = new javax.swing.JButton();
        printPairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        roundSpinner = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        standingsOutputButton = new javax.swing.JButton();
        crosstableOutputPrint = new javax.swing.JButton();
        pairingsOutputButton = new javax.swing.JButton();
        printOutputButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jNewTournamentMenuItem = new javax.swing.JMenuItem();
        jOpenTournamentMenuItem = new javax.swing.JMenuItem();
        jSaveTournamentMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jModifyTournamentMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jExitMenuItem = new javax.swing.JMenuItem();
        jStandingsMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jExtrasMenu = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jHelpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        playerDataTable.setModel(playerDataModel);
        jScrollPane1.setViewportView(playerDataTable);

        addPlayerButton.setText("Add Player");
        addPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        deletePlayerButton.setText("Delete Player");
        deletePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(addPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayerButton)
                    .addComponent(deletePlayerButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Player List", jPanel1);

        jTable2.setModel(pairingDataModel);
        jScrollPane3.setViewportView(jTable2);

        automaticPairButton.setText("Automatic");
        automaticPairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticPairButtonActionPerformed(evt);
            }
        });

        updatePairButton.setText("Update");

        modifyPairButton.setText("Modify");

        printPairButton.setText("Print");

        jLabel1.setText("Current Round");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(automaticPairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatePairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modifyPairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printPairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(automaticPairButton)
                    .addComponent(modifyPairButton)
                    .addComponent(jLabel1)
                    .addComponent(roundSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePairButton)
                    .addComponent(printPairButton))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pairing Page", jPanel2);

        standingsOutputButton.setText("Standings");
        standingsOutputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingsOutputButtonActionPerformed(evt);
            }
        });

        crosstableOutputPrint.setText("Crosstable");
        crosstableOutputPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crosstableOutputPrintActionPerformed(evt);
            }
        });

        pairingsOutputButton.setText("Pairings");

        printOutputButton.setText("Print");

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(standingsOutputButton)
                .addGap(18, 18, 18)
                .addComponent(crosstableOutputPrint)
                .addGap(18, 18, 18)
                .addComponent(pairingsOutputButton)
                .addGap(18, 18, 18)
                .addComponent(printOutputButton)
                .addGap(0, 555, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standingsOutputButton)
                    .addComponent(crosstableOutputPrint)
                    .addComponent(pairingsOutputButton)
                    .addComponent(printOutputButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Output", jPanel3);

        jFileMenu.setText("File");

        jNewTournamentMenuItem.setText("New Tournament");
        jNewTournamentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewTournamentMenuItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jNewTournamentMenuItem);

        jOpenTournamentMenuItem.setText("Open Tournament");
        jOpenTournamentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenTournamentMenuItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jOpenTournamentMenuItem);

        jSaveTournamentMenuItem.setText("Save Tournament");
        jSaveTournamentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveTournamentMenuItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jSaveTournamentMenuItem);
        jFileMenu.add(jSeparator1);

        jModifyTournamentMenuItem.setText("Modify Tournament");
        jFileMenu.add(jModifyTournamentMenuItem);
        jFileMenu.add(jSeparator2);

        jExitMenuItem.setText("Exit");
        jExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitMenuItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jExitMenuItem);

        jMenuBar1.add(jFileMenu);

        jStandingsMenu.setText("Standings");

        jMenuItem6.setText("Standings");
        jStandingsMenu.add(jMenuItem6);

        jMenuItem7.setText("Crosstable");
        jStandingsMenu.add(jMenuItem7);

        jMenuItem8.setText("Pairings");
        jStandingsMenu.add(jMenuItem8);

        jMenuBar1.add(jStandingsMenu);

        jExtrasMenu.setText("Extras");

        jMenuItem9.setText("Delete Current Round");
        jExtrasMenu.add(jMenuItem9);
        jExtrasMenu.add(jSeparator3);

        jMenuItem10.setText("Export Tournament in CSV Format");
        jExtrasMenu.add(jMenuItem10);

        jMenuBar1.add(jExtrasMenu);

        jHelpMenu.setText("Help");

        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        jHelpMenu.add(helpMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jHelpMenu.add(aboutMenuItem);

        jMenuBar1.add(jHelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "JPairing 1.0\n Author: Shaun Press");
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void addPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
        // TODO add your handling code here:
        playerDataModel.addBlankRow();
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void deletePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlayerButtonActionPerformed
        // TODO add your handling code here:
        int rowNo = playerDataTable.getSelectedRow();
        playerDataModel.deleteRow(rowNo);
    }//GEN-LAST:event_deletePlayerButtonActionPerformed

    private void jSaveTournamentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveTournamentMenuItemActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        
        int returnVal = fc.showSaveDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            
            // Handle file save here
        }                                         
        
    }//GEN-LAST:event_jSaveTournamentMenuItemActionPerformed

    private void jExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitMenuItemActionPerformed
        // TODO add your handling code here:
        int exit_code = JOptionPane.showConfirmDialog(this, "Do you mean to exit?","Exit Program",
                JOptionPane.YES_NO_OPTION);
        if (exit_code == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jExitMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int exit_code = JOptionPane.showConfirmDialog(this, "Do you mean to exit?","Exit Program",
                JOptionPane.YES_NO_OPTION);
        if (exit_code == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jNewTournamentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewTournamentMenuItemActionPerformed
        // TODO add your handling code here:
        TournamentDetailsDialog myDialog = new TournamentDetailsDialog(this,true);
        int dialogResult = myDialog.showDialog();
        
        if (dialogResult == 1 ) {
            tournamentDetails = new TournamentClass();
            tournamentDetails.setName(myDialog.getjNameTextField().getText());
            tournamentDetails.setPlace(myDialog.getjPlaceTextField().getText());
            
            this.setTitle(tournamentDetails.getName());
        }
        
        
        
    }//GEN-LAST:event_jNewTournamentMenuItemActionPerformed

    private void jOpenTournamentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenTournamentMenuItemActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        
        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            Path path = file.toPath();
            // Handle file read here
            readTournamentFile(path);
        }
    }//GEN-LAST:event_jOpenTournamentMenuItemActionPerformed

    private void automaticPairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticPairButtonActionPerformed
        // TODO add your handling code here:
        
        pairingDataModel.addRow();
        
    }//GEN-LAST:event_automaticPairButtonActionPerformed

    private void crosstableOutputPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crosstableOutputPrintActionPerformed
        // Output crosstable as string
        String crosstable_text = "Place \tPlayer Name \tRating \t";
        crosstable_text += playerDataModel.player_crosstable_list(2);
        jTextPane1.setText(crosstable_text);
    }//GEN-LAST:event_crosstableOutputPrintActionPerformed

    private void standingsOutputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingsOutputButtonActionPerformed
        // Output standings as string
        String standingsText = "Place \tPlayer Name \tRating \tMP \tVP \tVP% \tWins \n";
        standingsText += playerDataModel.player_standing_list(2);
        jTextPane1.setText(standingsText);
    }//GEN-LAST:event_standingsOutputButtonActionPerformed

    private void readTournamentFile(Path path) {
        // Reads from a aps format file and creates objects etc
        try {
            List<String> list_in = Files.readAllLines(path);
            tournamentDetails = new TournamentClass();
            tournamentDetails.setName(list_in.get(0));
            tournamentDetails.setPlace(list_in.get(1));
            tournamentDetails.setTotal_rounds(Integer.parseInt(list_in.get(4)));
            
            setTitle(tournamentDetails.getName());
            
            playerDataModel.resetPlayerList();
            int line_count = 6;
            String input_line = list_in.get(line_count);
            while (!input_line.equals("") ) {
                playerDataModel.addNewPlayer(input_line);
                line_count++;
                input_line = list_in.get(line_count);
            }
            
            // Load result details for each player
            line_count += 2;
            input_line = list_in.get(line_count).trim();
            while (!input_line.equals("")) {
                String[] result_data = input_line.split(" ");
                int player_id = Integer.parseInt(result_data[0]);
                for (int i=1; i < result_data.length; i++) {
                    String[] round_data = result_data[i].split(";");
                    playerDataModel.addPlayerResult(player_id+1, i, round_data);
                    
                    
                }
                
                
                line_count += 1;
                input_line = list_in.get(line_count).trim();
                
            }
            
        }
        catch (IOException e) {
            System.out.println(e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPairingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPairingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPairingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPairingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPairingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addPlayerButton;
    private javax.swing.JButton automaticPairButton;
    private javax.swing.JButton crosstableOutputPrint;
    private javax.swing.JButton deletePlayerButton;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JMenuItem jExitMenuItem;
    private javax.swing.JMenu jExtrasMenu;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenu jHelpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jModifyTournamentMenuItem;
    private javax.swing.JMenuItem jNewTournamentMenuItem;
    private javax.swing.JMenuItem jOpenTournamentMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem jSaveTournamentMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jStandingsMenu;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton modifyPairButton;
    private javax.swing.JButton pairingsOutputButton;
    private javax.swing.JTable playerDataTable;
    private javax.swing.JButton printOutputButton;
    private javax.swing.JButton printPairButton;
    private javax.swing.JSpinner roundSpinner;
    private javax.swing.JButton standingsOutputButton;
    private javax.swing.JButton updatePairButton;
    // End of variables declaration//GEN-END:variables
}
